### ISSUE TITLE
modulemd_add_platform tool issues with variables

### ISSUE THREAD

**Issue by fivaldi** [rpm-software-management/modulemd-tools#54]
/cc @ppisar 
Based on #53 re-factoring of the whole modulemd-tools package, I discovered some issues with modulemd_add_platform tool, see: 
```
modulemd_tools/modulemd_add_platform/modulemd_add_platform.py:77:17: F821 undefined name 'hexvalue'
modulemd_tools/modulemd_add_platform/modulemd_add_platform.py:211:24: F821 undefined name 'indent_configurations'
modulemd_tools/modulemd_add_platform/modulemd_add_platform.py:211:48: F821 undefined name 'indent_context'
modulemd_tools/modulemd_add_platform/modulemd_add_platform.py:214:43: F821 undefined name 'indent_configurations'
modulemd_tools/modulemd_add_platform/modulemd_add_platform.py:215:37: F821 undefined name 'indent_context'
modulemd_tools/modulemd_add_platform/modulemd_add_platform.py:220:25: F841 local variable 'this_context_is_old_platform' is assigned to but never used
modulemd_tools/modulemd_add_platform/modulemd_add_platform.py:238:25: F821 undefined name 'indent_configurations'
modulemd_tools/modulemd_add_platform/modulemd_add_platform.py:243:17: F841 local variable 'indent_context' is assigned to but never used
modulemd_tools/modulemd_add_platform/modulemd_add_platform.py:258:13: F841 local variable 'indent_configurations' is assigned to but never used
modulemd_tools/modulemd_add_platform/modulemd_add_platform.py:445:86: F821 undefined name 'e'
modulemd_tools/modulemd_add_platform/modulemd_add_platform.py:463:21: F524 '...'.format(...) is missing argument(s) for placeholder(s): 1
```

**Comment by ppisar** [comment]
Discovered, or some tool reported it? Because e.g. the first issue (modulemd_add_platform.py:77:17: F821 undefined name 'hexvalue') is not a bug:

~~~~
        hexleft = 0
        [...]
        for character in result.group(1):
            [...]
            if hexleft > 0:
                hexleft -= 1
→               hexvalue <<= 4
                hexvalue += int(character, base=16)
                if hexleft == 0:
                    output += chr(hexvalue)
                continue
            if escape:
                escape = False
                # \xHH, \uHHHH, \UHHHHHHHH
                if character == 'x':
                    hexleft = 2
                    hexvalue = 0
                elif character == 'u':
                    hexleft = 4
                    hexvalue = 0
                elif character == 'U':
                    hexleft = 8
                    hexvalue = 0
~~~~

The hexvalue variable is only accessed if hexleft > 0. Whenever hexleft is set to a positive value, at the same time hexvalue is initialized. Hence hexvalue is never accessed uninitialized.

When I look at the last issue (modulemd_add_platform.py:463:21: F524 '...'.format(...) is missing argument(s) for placeholder(s): 1), there is not format() call at the that line the current master HEAD (bfda40e7b59192dc729fd7fd733f48447b10025b).

Could you please tell me what tool you use, report issues against master code, and make sure before reporting that the issues are not false findings?

**Comment by fivaldi** [comment]
Thanks for your feedback, @ppisar. You may check either on the main branch or the #53 PR's branch using `tox -re flake8`. Please for the corresponding `noqa`s, if the reported issues are not relevant, I'd include it in the PR. Or, we may do it ex-post...

**Comment by fivaldi** [comment]
FYI 9f5f4367af436fdc6d92971f1a3a9a97017f75e4

**Comment by ppisar** [comment]
This was fixed with <https://github.com/rpm-software-management/modulemd-tools/pull/56>. You can close this issue.

**Comment by fivaldi** [comment]
#56 resolved.
